### ISSUE TITLE
貌似新版又出现Bug了……这次出问题的脚本还是Anti-Adblock Killer

### ISSUE THREAD

**Issue by Kara-ism** [gera2ld/Violentmonkey#22]
Gerald你好：

自从用了Opera以后，一直是你的插件Violent Monkey的爱用者；
前阵子跟Gerald你反馈了Anti-Adblock Killer不能在Violent Monkey运作的问题，
也很谢谢Gerald立马更新消除了不能使用的BUG；
可是最近的版本又不行了。
希望Gerald拨空能修复下，Violent Monkey很好用啊。
我确定了不是脚本的问题，因为相同的脚本在Google Chrome上使用Tamper Monkey可以运作的。

链结如下：
https://github.com/reek/anti-adblock-killer

**Comment by gera2ld** [comment]
方便给个简单的使用方法吗？我不知道怎么测试。。

**Comment by Kara-ism** [comment]
好的，在 http://antiblock.org/?p=v3&demo 这个页面可以进行测试，
安装Violent Monkey启用Anti-Adblock Killer出现的画面会是这个，
跟没有安装Anti-Adblock Killer脚本的显示内容是一样的。
![problem](https://cloud.githubusercontent.com/assets/9511279/8058191/50f5b024-0eea-11e5-8e47-8a5d63d4fbd6.PNG)

而在Google Chrome上安装Tamper Monkey的显示页面是这样的：
![work](https://cloud.githubusercontent.com/assets/9511279/8058222/8130fe60-0eea-11e5-8774-0ffb23798913.PNG)

Console的内容我看不懂，所以……

**Comment by gera2ld** [comment]
有没有真正起到antiblock作用的页面？我要测试一下运行过程中会不会出别的问题。

**Comment by Kara-ism** [comment]
好得，这里有几个网站是采用Antiblock的脚本

**Comment by gera2ld** [comment]
好的，我测试可以用了，我会尽快发布新版

**Comment by Kara-ism** [comment]
Gerald你好，谢谢你！
